server:
  port: 8084
spring:
  application:
    name: policy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://120.78.91.241:3306/policy