server:
  port: 8001
spring:
  application:
    name: cloud-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 120.78.91.241:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
      routes:  # 路由
        - id: finance #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://finance # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/finance/** # 断言，路径相匹配进行路由
        - id: policy
          uri: lb://policy
          predicates:
            - Path=/policy/**
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**